# Generated by Django 3.1.1 on 2021-01-08 09:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(default='NA')),
                ('name', models.TextField(default='NA')),
                ('ensembl_id', models.TextField(default='NA')),
                ('entrez_id', models.TextField(default='NA')),
                ('hgnc_id', models.TextField(default='NA')),
                ('alias_list', jsonfield.fields.JSONField(default=[])),
                ('alternative_name_list', jsonfield.fields.JSONField(default=[])),
                ('description', models.TextField(default='NA')),
                ('localisation', models.TextField(default='NA')),
                ('gene_type', models.TextField(default='NA')),
                ('pmid_list', jsonfield.fields.JSONField(default=[])),
                ('pathway_list', jsonfield.fields.JSONField(default=[])),
                ('gene_card_link', models.TextField(default='NA')),
                ('ensembl_link', models.TextField(default='NA')),
            ],
        ),
    ]
